spring:

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
     # url: jdbc:mysql://139.159.221.252:3306/yblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
     # username: root
     # password: '!Xx19711021'
      url: jdbc:mysql://localhost:3306/yblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 'x19711021'

  mybatis-plus:
    mapper-locations: classpath*:/mapper/**Mapper.xml

  freemarker:
    suffix: .ftl
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##



